[package]
name = "evcsv"
version = "0.1.0"
authors = ["yukimemi <yukimemi@gmail.com>"]
edition = "2018"

[dependencies]
evtx = "0.11.0"
csv = "1.0.7"
clap = "2.33.0"
failure = "0.1.5"
pretty_env_logger = "0.5.0"
log = "0.4.6"
